CREATE TABLE IF NOT EXISTS `JOBDETAIL` (
  `JOBDETAIL_ID` VARCHAR(255) NOT NULL COMMENT '岗位描述id',
  `JOBDETAIL` VARCHAR(5120) COMMENT '岗位描述',
  PRIMARY KEY (`JOBDETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `COMPANY` (
  `CMP_ID` VARCHAR(255) NOT NULL COMMENT '公司id',
  `CMP_NAME` VARCHAR(255) NOT NULL COMMENT '公司名称',
  `CMP_SCALE_MIN` INT COMMENT '公司规模-起',
  `CMP_SCALE_MAX` INT COMMENT '公司规模-止',
  `CMP_LINK` VARCHAR(1024) COMMENT '公司链接',
  `CMP_STAGE` VARCHAR(1024) COMMENT '公司融资情况',
  `CMP_LOGO` VARCHAR(1024) COMMENT '公司logo',
  `CMP_INDUSTRY` VARCHAR(255) COMMENT '公司行业',
  PRIMARY KEY (`CMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `RECRUITER` (
  `REC_ID` VARCHAR(255) NOT NULL COMMENT '招聘者ID',
  `IM_ID` VARCHAR(255) NOT NULL COMMENT 'imid',
  `IM_USERTYPE` VARCHAR(255) NOT NULL COMMENT 'im_usertype',
  `REC_NAME` VARCHAR(1024) NOT NULL COMMENT '招聘者名称',
  `REC_TITLE` VARCHAR(1024) COMMENT '招聘者抬头',
  `REC_PIC` VARCHAR(1024) COMMENT '招聘者头像',
  PRIMARY KEY (`REC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `JOBLABEL` (
  `LABEL_ID` INT AUTO_INCREMENT NOT NULL COMMENT '标签ID',
  `LABEL_NAME` VARCHAR(255) NOT NULL COMMENT '标签内容',
  PRIMARY KEY (`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `JOBCARD` (
  `JOBCARD_ID` INT NOT NULL COMMENT '岗位ID',
  `JOB_NAME` VARCHAR(255) NOT NULL COMMENT '岗位名称',
  `JOB_REFER` VARCHAR(255) COMMENT '关键字',
  `JOB_SALARY_MIN` INT COMMENT '薪资起',
  `JOB_SALARY_MAX` INT COMMENT '薪资止',
  `JOB_SALARY_COUNT` INT COMMENT '发薪次数',
  `JOB_EDU` VARCHAR(255) NOT NULL COMMENT '教育要求',
  `JOB_CITY` VARCHAR(255) NOT NULL COMMENT '所在城市',
  `JOB_DQ` VARCHAR(255) COMMENT '所在城市区划',
  `JOB_LINK` VARCHAR(1024) COMMENT '岗位链接',
  `JOB_KIND` INT COMMENT '岗位分类',
  `JOB_EXP_MIN` INT COMMENT '经验要求-起',
  `JOB_EXP_MAX` INT COMMENT '经验要求-止',
  `JOB_UPDATE` DATE NOT NULL COMMENT '岗位更新时间',
  `CMP_ID_ID` VARCHAR(255) NOT NULL COMMENT '公司ID',
  `REC_ID_ID` VARCHAR(255) NOT NULL COMMENT '招聘者ID',
  `JOBDETAIL_ID_ID` VARCHAR(255) COMMENT '岗位详情ID',
  PRIMARY KEY (`JOBCARD_ID`),
  CONSTRAINT `FOREIGN_COMPANY` FOREIGN KEY (`CMP_ID_ID`) REFERENCES `COMPANY` (`CMP_ID`),
  CONSTRAINT `FOREIGN_RECRUITER` FOREIGN KEY (`REC_ID_ID`) REFERENCES `RECRUITER` (`REC_ID`),
  CONSTRAINT `FOREIGN_JOBDETAIL` FOREIGN KEY (`JOBDETAIL_ID_ID`) REFERENCES `JOBDETAIL` (`JOBDETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `CARDLABEL` (
  `CARDLABEL_ID` INT AUTO_INCREMENT NOT NULL COMMENT 'CARDLABELID',
  `JOBCARD_ID_ID` INT NOT NULL COMMENT '岗位ID',
  `LABEL_ID_ID` INT NOT NULL COMMENT '标签ID',
  PRIMARY KEY (`CARDLABEL_ID`),
  UNIQUE KEY (`JOBCARD_ID_ID`,`LABEL_ID_ID`),
  CONSTRAINT `FOREIGN_JOBCARD` FOREIGN KEY (`JOBCARD_ID_ID`) REFERENCES `JOBCARD` (`JOBCARD_ID`),
  CONSTRAINT `FOREGIN_JOBLABEL` FOREIGN KEY (`LABEL_ID_ID`) REFERENCES `JOBLABEL` (`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;