CREATE TABLE
    IF NOT EXISTS "RECRUITER_INFO" (
        "REC_ID" VARCHAR(64) NOT NULL,
        "IM_ID" VARCHAR(64) NOT NULL,
        "IM_USERTYPE" VARCHAR(32) NOT NULL,
        "REC_NAME" VARCHAR(64) NOT NULL,
        "REC_TITLE" VARCHAR(128),
        "REC_PIC" VARCHAR(256),
        "REC_SOURCE" VARCHAR(256),
        PRIMARY KEY ("REC_ID")
    );