CREATE TABLE
    IF NOT EXISTS "COMPANY_INFO" (
        "CMP_ID" VARCHAR(32) NOT NULL,
        "CMP_NAME" VARCHAR(128) NOT NULL,
        "CMP_SCALE_MIN" INT,
        "CMP_SCALE_MAX" INT,
        "CMP_LINK" VARCHAR(256),
        "CMP_STAGE" VARCHAR(64),
        "CMP_LOGO" VARCHAR(256),
        "CMP_INDUSTRY" VARCHAR(64),
        "CMP_SOURCE" VARCHAR(64),
        PRIMARY KEY ("CMP_ID")
    );