CREATE TABLE
    IF NOT EXISTS "JOB_CARD" (
        "JOBCARD_ID" VARCHAR(64) NOT NULL,
        "JOB_NAME" VARCHAR(64) NOT NULL,
        "JOB_REFER" VARCHAR(255),
        "JOB_SALARY_MIN" INT,
        "JOB_SALARY_MAX" INT,
        "JOB_SALARY_COUNT" INT,
        "JOB_EDU" VARCHAR(64) NOT NULL,
        "JOB_CITY" VARCHAR(64) NOT NULL,
        "JOB_DQ" VARCHAR(64),
        "JOB_LINK" VARCHAR(256),
        "JOB_KIND" INT,
        "JOB_EXP_MIN" INT,
        "JOB_EXP_MAX" INT,
        "JOB_LABEL" VARCHAR(32) [],
        "JOB_UPDATE" DATE NOT NULL,
        "CMP_ID" VARCHAR(32) NOT NULL,
        "REC_ID" VARCHAR(64) NOT NULL,
        PRIMARY KEY ("JOBCARD_ID")
    )