# Generated by Django 4.2.6 on 2023-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, help_text='用户id', max_length=12, unique=True)),
                ('user_phone', models.CharField(default=0, help_text='手机号码', max_length=16)),
                ('user_email', models.EmailField(help_text='用户邮箱', max_length=254)),
                ('user_password', models.CharField(help_text='加密用户密码', max_length=128)),
                ('user_create', models.DateTimeField(help_text='创建时间')),
                ('user_update', models.DateTimeField(help_text='更新时间')),
                ('user_authority', models.IntegerField(default=0, help_text='用户权限')),
                ('user_state', models.IntegerField(default=0, help_text='用户状态')),
                ('user_character', models.IntegerField(default=0, help_text='用户角色')),
            ],
            options={
                'db_table': 'user_auth',
            },
        ),
    ]
